export const HOME = 'home';
export const PROFILE = 'profile';
export const SKILLS = 'skills';
export const PROJECTS = 'projects';
export const CONTACT = 'contact';
export const SUCCESS = 'success';
export const CV_LINK =
  'https://drive.google.com/file/d/1lqqpxVKLwpqRglfFH8nd3SZKoo4lU7D_/view?usp=sharing';
export const LINK_ARRAY = [HOME, PROFILE, SKILLS, PROJECTS,CONTACT];
